#!/bin/bash

#!/bin/bash

if [ -z $1 ]
then
    echo "usage conf <file>.[md]"
    exit 1
fi

if ! echo $1 | egrep '\md$' > /dev/null
then
    FILE=$1md
    BASE=${1:0: -1}
else
    FILE=$1
    BASE=$(echo $1 | sed 's/\.md$//')
fi

# Removing line wraps
out=$(mktemp)
pandoc -f markdown -t html $FILE | pandoc -f html -t markdown --wrap=none > $out
/opt/node-v8.7.0-linux-x64/bin/markdown2confluence $out

trap "rm $out" EXIT INT TERM
