#!/bin/bash

if [ -z $1 ]
then
    echo "usage html <file>.[md]"
    exit 1
fi

if ! echo $1 | egrep '\md$' > /dev/null
then
    FILE=$1md
    BASE=${1:0: -1}
else
    FILE=$1
    BASE=$(echo $1 | sed 's/\.md$//')
fi

pandoc --quiet -f markdown+smart --standalone \
       --mathjax=https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js?config=TeX-AMS_CHTML-full \
       --filter pandoc-plantuml-filter \
       -o $BASE.html $FILE 

