#!/bin/bash

if [ -z $1 ]
then
    echo "usage mdunrwap <file>.[md]"
    exit 1
fi

if ! echo $1 | egrep '\md$' > /dev/null
then
    FILE=$1md
    BASE=${1:0: -1}
else
    FILE=$1
    BASE=$(echo $1 | sed 's/\.md$//')
fi

out=$(mktemp)
pandoc -f markdown -t html $FILE | pandoc -f html -t markdown --wrap=none > $out
cat $out

trap "rm $out" EXIT INT TERM
